# This file is part of Solar Eclipse Model.
# Copyright (C) 2025 Eric Broens
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Actual YAML starts below
common:
  output_dir: ./results 
  data_file: ./data/image_data_Chile_20190702.txt  #file with measurements
  date_column: "date"  #column header of the date time column
  time_column: "time"
  flux_column: "G_norm"   #column header of the (normalized) flux to be modelled
  color_channel: G  #used in the filenames and corner plot
  sigma_data: 0.001  #estimated accuracy of the measured flux
  plot_config:
    plot_color: green
    plot_marker_symbol: "."
    plot_range:
      start_datetime: "2019-07-02 19:00:00"
      end_datetime: "2019-07-02 21:50:00"
    eclipse_times: #only used for plotting purposes
      tc1: "2019-07-02 19:23:16"
      tc2: "2019-07-02 20:38:31" #Remove or comment out for partial eclipses
      tc3: "2019-07-02 20:41:04" #Remove or comment out for partial eclipses
      tc4: "2019-07-02 21:46:50"
    inset:
      enabled: true
      loc: "lower left"
      width: "80%"
      height: "80%"
      bbox_to_anchor: [0.075, 0.30, 0.30, 0.30]
      bbox_transform: "axes"  # or "figure", or "data" 
      x_lim: ["2019-07-02 20:35:00", "2019-07-02 20:45:00"]
      y_lim: [-0.02, 0.05]
      mark_inset_loc: [1, 3]  #Corners to use for connecting the inset axes and the area in the parent axes.
models:
  linear:
    limb_dark: linear
    moon_radius: 1.0
    atm_ext: 0.01
    u: [0.3]
    lat: -29.88606
    lon: -70.68380
    mcmc: true
    fit_params:
      u1:
        prior: [-1.0, 1.0]
        plot_label: "$u_{1}$"
      atm_ext:
        prior: [0.0, 0.2]
        plot_label: "$\\tau_{{color_channel}}$"
      moon_radius:
        prior: [0.9, 1.1]
        plot_label: "$r_{m}$"
      log_sigma_jitter:
        prior: [1.0e-5, 1.0e-2]  # will be converted to log
        plot_label: "$\\log(\\sigma_\\mathrm{jitter})$"
    plotting:
        color: green
        line_style: "-"
        residuals_marker: "."
        model_label: linear LD     
  linear_mr:
    limb_dark: linear
    moon_radius: 1.037
    atm_ext: 0.01
    u: [0.3]
    lat: -29.88606
    lon: -70.68380
    mcmc: true
    fit_params:
      u1:
        prior: [-1.0, 1.0]
        plot_label: "$u_{1}$"
      atm_ext:
        prior: [0.0, 0.2]
        plot_label: "$\\tau_{{color_channel}}$"
      log_sigma_jitter:
        prior: [1.0e-5, 1.0e-2]  # will be converted to log
        plot_label: "$\\log(\\sigma_\\mathrm{jitter})$"
    plotting:
        color: k
        line_style: "--"
        residuals_marker: "."    
        model_label: "linear LD, $r_m$ = 1.037"           
  quadratic:
    limb_dark: quadratic
    moon_radius: 1.037
    atm_ext: 0.01
    u: [0.1, 0.3]
    lat: -29.88606
    lon: -70.68380
    mcmc: true
    fit_params:
      u1:
        prior: [-1.0, 3.0]
        plot_label: "$u_{1}$"
      u2:
        prior: [-3.0, 3.0]
        plot_label: "$u_{2}$"        
      atm_ext:
        prior: [0.0, 0.2]
        plot_label: "$\\tau_{{color_channel}}$"
      moon_radius:
        prior: [0.9, 1.1]
        plot_label: "$r_{m}$"         
      log_sigma_jitter:
        prior: [1.0e-5, 1.0e-2]  # will be converted to log
        plot_label: "$\\log(\\sigma_\\mathrm{jitter})$"
    plotting:
        color: k
        line_style: ":"
        residuals_marker: "*"    
        model_label: "quadratic LD"    
  uniform:
    limb_dark: uniform
    moon_radius: 1.0
    atm_ext: 0.01
    u: []
    lat: -29.88606
    lon: -70.68380
    mcmc: true
    fit_params:
      atm_ext:
        prior: [-0.1, 0.1]
        plot_label: "$u_{1}$"        
      moon_radius:
        prior: [0.9, 1.1]
        plot_label: "$r_{m}$"      
      log_sigma_jitter:
        prior: [1.0e-6, 1.0e-1]
        plot_label: "$\\log(\\sigma_\\mathrm{jitter})$"  
    plotting:
        color: k
        line_style: "-"
        residuals_marker: "+"
        model_label: uniform LD
  lat_lon:
    limb_dark: linear
    moon_radius: 1.037
    atm_ext: 0.082
    u: [0.41]
    lat: -32.0
    lon: -67.0    
    nwalkers: 128
    nsteps: 3000
    mcmc: true
    fit_params:
      lat: 
        prior: [-40.0, -20.0]
        plot_label: "lat"
      lon: 
        prior: [-80.0, -60.0]
        plot_label: "lon"          
      log_sigma_jitter:
        prior: [1.0e-6, 1.0e-1]
        plot_label: "$\\log(\\sigma_\\mathrm{jitter})$"  
    plotting:
        color: red
        line_style: "-"
        residuals_marker: "d"
        model_label: lat/lon    
        
