# .github/workflows/deploy_docs.yml
name: Deploy Sphinx Docs

on:
  push:
    branches:
      - main  # Or 'master', depending on your default branch name
    paths:
      - 'docs/**' # Trigger only when changes are made in the docs/ directory
      - 'requirements.in' # Or requirements.txt if you don't use pip-tools
      - 'setup.py' # If your project has a setup.py
      - 'pyproject.toml' # If your project uses pyproject.toml for dependencies

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Using a specific stable Python version

    # --- NEW: Install system-level dependencies for Matplotlib ---
    - name: Install system dependencies for Matplotlib
      run: |
        sudo apt-get update
        sudo apt-get install -y libatlas-base-dev libpng-dev libfreetype6-dev zlib1g-dev texlive-latex-base

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pip-tools
        pip-compile requirements.in
        pip install -r requirements.txt
        pip install 'imageio<2.30'

    - name: Configure Matplotlib Backend (Explicitly)
      run: |
        python -c "import matplotlib; matplotlib.use('Agg'); print(f'Matplotlib backend set to: {matplotlib.get_backend()}');"

    - name: Diagnose Matplotlib Backend (Verify)
      run: |
        python -c "import matplotlib; print(f'Matplotlib backend (after config): {matplotlib.get_backend()}');"

    - name: Build Sphinx documentation
      run: |
        cd docs/
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        publish_branch: gh-pages

